// import { FoodInfo } from '../model/DataModels'
//
// export let tomato: FoodInfo = new FoodInfo(1,'番茄', $r('app.media.tomato'), "蔬菜", "2023-11-27", "左边", "一层", "临期", "2个", false)
//
// export let walnut: FoodInfo = new FoodInfo(2,'坚果', $r('app.media.walnut'), "零食", "2023-12-20", "左边", "二层", "新鲜", "0.5千克", false)
//
// export let cucumber: FoodInfo = new FoodInfo(3,'黄瓜', $r('app.media.cucumber'), "蔬菜", "2023-12-27", "左边", "三层", "新鲜", "3个", false)
//
// export let blueberry: FoodInfo = new FoodInfo(4,'蓝莓', $r('app.media.blueberry'), "水果", "2023-12-27", "左边", "三层", "新鲜", "3个", false)
//
// export let crab: FoodInfo = new FoodInfo(5,'螃蟹', $r('app.media.crab'), "海鲜", "2023-12-27", "左边", "三层", "新鲜", "3个", true)
//
// export let iceCream: FoodInfo = new FoodInfo(6,'雪糕', $r('app.media.icecream'), "零食", "2023-11-20", "右边", "二层", "过期", "1个", true)
//
// export let mockFoods: Array<FoodInfo> = [
//   tomato, walnut, cucumber, blueberry, crab, iceCream
// ]